name: Build Windows Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set Flutter directory
      run: echo "FLUTTER_ROOT=flutter_sdk" >> $GITHUB_ENV

    - name: Download Flutter SDK
      run: curl -L -o flutter.zip https://storage.googleapis.com/flutter_infra_release/releases/stable/windows/flutter_windows_3.3.8-stable.zip

    - name: Create Flutter directory
      run: powershell -Command "New-Item -Path 'flutter_sdk' -ItemType Directory -Force"

    - name: Extract Flutter SDK
      run: powershell -Command "Expand-Archive -Path 'flutter.zip' -DestinationPath 'flutter_sdk'"

    - name: Add Flutter to PATH
      run: echo "${{ github.workspace }}\\flutter_sdk\\flutter\\bin" >> $GITHUB_PATH

    - name: Set PATH environment variable
      env:
        PATH: ${{ github.workspace }}\\flutter_sdk\\flutter\\bin:${{ github.workspace }}\\flutter_sdk\\flutter\\bin\\cache\\dart-sdk\\bin:$PATH

    - name: Verify Flutter installation
      run: flutter --version

    - name: Install dependencies
      run: flutter pub get
      working-directory: mrt_wallet

    - name: Enable Windows desktop
      run: flutter config --enable-windows-desktop
      working-directory: mrt_wallet

    - name: Build Windows
      run: flutter build windows --release
      working-directory: mrt_wallet

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: windows-build
        path: mrt_wallet/build/windows/runner/Release/
